import { useState, useEffect } from 'react'
import { Plus, Trash2, CheckCircle2, RotateCcw, Info, Bed, Stethoscope } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { NativeSelect } from '@/components/ui/native-select'
import { FormField } from '@/components/ui/form-field'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { useBillingConfig } from '@/context/BillingConfigContext'
import { useServiceEntries } from '@/context/ServiceEntriesContext'
import { useToast } from '@/context/ToastContext'
import { RoomTransferPanel } from '@/components/shared/RoomTransferPanel'
import { formatCurrency } from '@/lib/utils'
import { BILLING_TYPES } from '@/data/mockData'
import { cn } from '@/lib/utils'
import {
  validateServiceCart,
  validateReturnCart,
  validatePositiveNumber,
  firstError,
  trimText,
} from '@/lib/validation'
import { isMaternityAdmission } from '@/lib/maternity'
import { AnimatePresence, motion, useReducedMotion, fadeUp, revealTransition } from '@/lib/motion'
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip'

export function ServiceRecordBuilder({
  patientId,
  patientName,
  patient,
  source,
  recordedBy,
  hideMoney = false,
  autoApprove = false,
  editRecord = null,
  onDone,
}) {
  const { toast } = useToast()
  const { categories, settings } = useBillingConfig()
  const {
    buildServiceLine,
    buildReturnLine,
    submitDailyRecord,
    submitPharmacyReturn,
    getPendingEditableRecord,
    getPatientRecords,
  } = useServiceEntries()

  const manualCategories = categories.filter((c) => c.billingType !== BILLING_TYPES.AUTOMATIC_DAILY)
  const pharmacyCategory = categories.find((c) => c.id === 'pharmacy')

  const [mode, setMode] = useState('services')
  const [activeCategory, setActiveCategory] = useState(manualCategories[0]?.name || categories[0]?.name || '')
  const [cart, setCart] = useState([])
  const [returnCart, setReturnCart] = useState([])
  const [checkedItems, setCheckedItems] = useState({})
  const [form, setForm] = useState({ serviceName: '', quantity: 1, notes: '' })
  const [returnForm, setReturnForm] = useState({ serviceName: '', quantity: 1, reason: '' })
  const [editingRecordId, setEditingRecordId] = useState(null)
  const [editingReturnId, setEditingReturnId] = useState(null)
  const [paperSlipRef, setPaperSlipRef] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const maternity = isMaternityAdmission(patient)
  const [subjectType, setSubjectType] = useState('mother')
  const reducedMotion = useReducedMotion()

  const today = new Date().toISOString().split('T')[0]
  const pendingDaily = getPendingEditableRecord(patientId, 'daily_services', today, maternity ? subjectType : 'mother')
  const pendingReturn = getPendingEditableRecord(patientId, 'pharmacy_return', today, maternity ? subjectType : 'mother')
  const activeCat = categories.find((c) => c.name === activeCategory)

  useEffect(() => {
    setCheckedItems({})
    setForm({ serviceName: '', quantity: 1, notes: '' })
  }, [activeCategory])

  const draftServiceLines = (record) =>
    (record?.services || []).filter((s) => s.category !== 'Room Services' && s.category !== 'Doctor Visits')

  const startEditingPendingDaily = () => {
    if (!pendingDaily) return
    setCart(draftServiceLines(pendingDaily))
    setEditingRecordId(pendingDaily.id)
  }

  const startEditingPendingReturn = () => {
    if (!pendingReturn) return
    setReturnCart(pendingReturn.returnItems || [])
    setEditingReturnId(pendingReturn.id)
  }

  useEffect(() => {
    if (!editRecord?.id) return
    if (editRecord.status !== 'pending' || editRecord.autoGenerated) return
    if (editRecord.subjectType === 'baby' || editRecord.subjectType === 'mother') {
      setSubjectType(editRecord.subjectType)
    }
    if (editRecord.type === 'pharmacy_return') {
      setMode('returns')
      setReturnCart(editRecord.returnItems || [])
      setEditingReturnId(editRecord.id)
      setCart([])
      setEditingRecordId(null)
      return
    }
    setMode('services')
    setCart(draftServiceLines(editRecord))
    setEditingRecordId(editRecord.id)
    setReturnCart([])
    setEditingReturnId(null)
  }, [editRecord?.id])

  const resetSubjectDraft = (nextSubject) => {
    setSubjectType(nextSubject)
    setCart([])
    setReturnCart([])
    setEditingRecordId(null)
    setEditingReturnId(null)
  }

  const updateCartLine = (idx, patch) => {
    setCart((prev) =>
      prev.map((line, i) => {
        if (i !== idx) return line
        const next = { ...line, ...patch }
        const qty = Number(next.quantity)
        if (Number.isFinite(qty) && qty > 0) next.total = qty * Number(next.unitPrice || 0)
        return next
      })
    )
  }

  const updateReturnLine = (idx, patch) => {
    setReturnCart((prev) =>
      prev.map((line, i) => {
        if (i !== idx) return line
        const next = { ...line, ...patch }
        const qty = Number(next.quantity)
        if (Number.isFinite(qty) && qty > 0) next.total = qty * Number(next.unitPrice || 0)
        return next
      })
    )
  }

  const toggleCheckItem = (serviceName, defaultQty = 1) => {
    setCheckedItems((prev) => {
      const next = { ...prev }
      if (next[serviceName] !== undefined) delete next[serviceName]
      else next[serviceName] = defaultQty
      return next
    })
  }

  const setItemQuantity = (serviceName, qty) => {
    const num = Math.max(1, Number(qty) || 1)
    setCheckedItems((prev) => ({ ...prev, [serviceName]: num }))
  }

  const addCheckedToCart = () => {
    const names = Object.keys(checkedItems)
    if (names.length === 0) {
      toast({ title: 'Select at least one item', variant: 'destructive' })
      return
    }
    if (activeCat?.billingType === BILLING_TYPES.QUANTITY) {
      for (const name of names) {
        const qtyErr = validatePositiveNumber(checkedItems[name], 'Quantity', { min: 0 })
        if (qtyErr) {
          toast({ title: 'Invalid quantity', description: qtyErr, variant: 'destructive' })
          return
        }
      }
    }
    const lines = names.map((name) => {
      const svc = activeCat.services.find((s) => s.name === name)
      return buildServiceLine({
        category: activeCategory,
        serviceName: name,
        quantity: checkedItems[name],
        unitPrice: svc.price,
        notes: '',
      })
    })
    setCart((prev) => [...prev, ...lines])
    setCheckedItems({})
    toast({ title: 'Items added', description: `${lines.length} item(s) added to record`, variant: 'success' })
  }

  const renderChecklistPanel = (description) => (
    <div>
      <p className="text-xs text-muted-foreground mb-3">{description}</p>
      <div className="grid gap-2 sm:grid-cols-2 mb-4">
        {activeCat.services.map((svc) => {
          const checked = checkedItems[svc.name] !== undefined
          return (
            <div
              key={svc.name}
              className={cn(
                'flex items-center gap-3 rounded-lg border bg-card p-3 transition-[border-color,background-color,box-shadow] duration-140 ease-out-soft',
                checked ? 'border-primary bg-primary/5 shadow-sm' : 'hover:border-primary/25 hover:bg-muted/40 hover:shadow-sm'
              )}
            >
              <input
                type="checkbox"
                className="h-4 w-4 rounded border-input shrink-0"
                checked={checked}
                onChange={() => toggleCheckItem(svc.name)}
              />
              <span className="flex-1 text-sm font-medium min-w-0">{svc.name}</span>
              {!hideMoney && (
                <span className="shrink-0 text-xs tabular-nums text-muted-foreground">{formatCurrency(svc.price)}</span>
              )}
              <div className="flex items-center gap-1 shrink-0">
                <Label className="text-xs text-muted-foreground sr-only">Qty</Label>
                <Input
                  type="number"
                  min="1"
                  className="h-8 w-16 text-center tabular-nums"
                  value={checked ? checkedItems[svc.name] : 1}
                  disabled={!checked}
                  onChange={(e) => setItemQuantity(svc.name, e.target.value)}
                  aria-label={`${svc.name} quantity`}
                />
              </div>
            </div>
          )
        })}
      </div>
      <Button type="button" onClick={addCheckedToCart} disabled={Object.keys(checkedItems).length === 0}>
        <Plus className="h-4 w-4 mr-1" /> Add Selected ({Object.keys(checkedItems).length})
      </Button>
    </div>
  )

  const handleDoneServices = async () => {
    const cartErrors = validateServiceCart(cart, activeCategory, categories)
    if (Object.keys(cartErrors).length) {
      toast({ title: 'Validation error', description: firstError(cartErrors), variant: 'destructive' })
      return
    }

    if (editingRecordId) {
      const existing = getPatientRecords(patientId).find((r) => r.id === editingRecordId)
      if (existing && existing.status !== 'pending') {
        toast({ title: 'Record is locked', description: 'Approved or rejected records cannot be edited.', variant: 'destructive' })
        return
      }
    }

    const slip = trimText(paperSlipRef)
    if (slip) {
      const cartKey = cart.map((s) => `${s.serviceName}:${s.quantity}`).sort().join('|')
      const duplicate = getPatientRecords(patientId).find((r) => {
        if (r.recordDate !== today || r.status === 'rejected') return false
        const key = (r.services || []).map((s) => `${s.serviceName}:${s.quantity}`).sort().join('|')
        return key === cartKey
      })
      if (duplicate && !window.confirm('A record with the same services already exists for today. Submit anyway?')) {
        return
      }
    }

    const servicesPayload = cart.map((line, i) =>
      i === 0 && slip ? { ...line, notes: `${line.notes || ''} Paper slip #${slip}`.trim() } : line
    )

    setSubmitting(true)
    const count = cart.length
    try {
      await submitDailyRecord({
        patientId,
        services: servicesPayload,
        source,
        recordedBy,
        existingRecordId: editingRecordId,
        recordDate: today,
        subjectType: maternity ? subjectType : 'mother',
        babyId: maternity && subjectType === 'baby' ? patient?.baby?.id : null,
      })
      setCart([])
      setEditingRecordId(null)
      setPaperSlipRef('')
      setCheckedItems({})
      toast({
        title: autoApprove ? 'Record Saved' : 'Daily Record Submitted',
        description: autoApprove
          ? `${patientName} — ${count} service(s) added`
          : `${patientName} — sent to reception for approval`,
        variant: 'success',
      })
      onDone?.()
    } catch (err) {
      toast({ title: 'Submit failed', description: err.message, variant: 'destructive' })
    } finally {
      setSubmitting(false)
    }
  }

  const addToReturnCart = () => {
    if (!returnForm.serviceName) {
      toast({ title: 'Select a medicine', variant: 'destructive' })
      return
    }
    const qtyErr = validatePositiveNumber(returnForm.quantity, 'Return quantity', { min: 0 })
    if (qtyErr) {
      toast({ title: 'Invalid quantity', description: qtyErr, variant: 'destructive' })
      return
    }
    const med = pharmacyCategory?.services.find((s) => s.name === returnForm.serviceName)
    if (!med) return
    const line = buildReturnLine({
      serviceName: returnForm.serviceName,
      quantity: returnForm.quantity,
      unitPrice: med.price,
      reason: returnForm.reason,
    })
    setReturnCart((prev) => [...prev, line])
    setReturnForm({ serviceName: '', quantity: 1, reason: '' })
    toast({ title: 'Added to return', description: returnForm.serviceName, variant: 'success' })
  }

  const handleDoneReturn = async () => {
    const returnErrors = validateReturnCart(returnCart)
    if (Object.keys(returnErrors).length) {
      toast({ title: 'Validation error', description: firstError(returnErrors), variant: 'destructive' })
      return
    }
    if (editingReturnId) {
      const existing = getPatientRecords(patientId).find((r) => r.id === editingReturnId)
      if (existing && existing.status !== 'pending') {
        toast({ title: 'Record is locked', description: 'Approved or rejected records cannot be edited.', variant: 'destructive' })
        return
      }
    }
    setSubmitting(true)
    try {
      await submitPharmacyReturn({
        patientId,
        returnItems: returnCart,
        source,
        recordedBy,
        existingRecordId: editingReturnId,
        subjectType: maternity ? subjectType : 'mother',
        babyId: maternity && subjectType === 'baby' ? patient?.baby?.id : null,
      })
      setReturnCart([])
      setEditingReturnId(null)
      toast({
        title: autoApprove ? 'Return Saved' : 'Pharmacy Return Submitted',
        description: `${patientName} — reception will cross-check`,
        variant: 'success',
      })
      onDone?.()
    } catch (err) {
      toast({ title: 'Submit failed', description: err.message, variant: 'destructive' })
    } finally {
      setSubmitting(false)
    }
  }

  const renderCategoryPanel = () => {
    if (!activeCat) return null

    if (activeCat.billingType === BILLING_TYPES.AUTOMATIC_DAILY) {
      const isRoom = activeCat.id === 'room'
      return (
        <div className="space-y-6">
          <div className="rounded-xl border bg-muted/30 p-6 text-center space-y-3">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary mx-auto">
              {isRoom ? <Bed className="h-6 w-6" /> : <Stethoscope className="h-6 w-6" />}
            </div>
            <h3 className="font-semibold">{activeCat.name}</h3>
            <p className="text-sm text-muted-foreground max-w-md mx-auto">
              {isRoom
                ? 'Room charges are calculated automatically from the patient\'s room assignment history.'
                : 'This category is billed automatically once per admission day.'}
            </p>
            {!isRoom && !hideMoney && (
              <p className="text-sm font-medium text-primary">
                Fallback daily fee: {formatCurrency(settings.dailyDoctorVisitFee)}
                <span className="block text-xs font-normal text-muted-foreground">
                  Assigned doctors use their own catalog price. This fee is used only when a doctor has no price.
                </span>
              </p>
            )}
            <div className="flex items-start gap-2 text-left text-xs text-muted-foreground bg-background rounded-lg p-3 border max-w-md mx-auto">
              <Info className="h-4 w-4 shrink-0 mt-0.5" />
              <span>
                {isRoom
                  ? 'If the room changes, the correct rate applies from the transfer date onward. No manual entry needed.'
                  : 'Reception can disable a specific day\'s doctor visit if the doctor did not visit. No manual entry needed.'}
              </span>
            </div>
          </div>
          {isRoom && !hideMoney && (
            <div className="border-t pt-4 text-left">
              <RoomTransferPanel patientId={patientId} assignedBy={recordedBy} />
            </div>
          )}
        </div>
      )
    }

    if (
      activeCat.billingType === BILLING_TYPES.SELECTION ||
      activeCat.billingType === BILLING_TYPES.QUANTITY
    ) {
      return renderChecklistPanel(`${activeCat.description} — select items and set quantity for each.`)
    }

    return null
  }

  return (
    <TooltipProvider delayDuration={400}>
    <Card className="shadow-md">
      <CardHeader>
        <p className="text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Record builder</p>
        <CardTitle className="mt-1 text-lg">Charge Entry — {patientName}</CardTitle>
        <CardDescription>
          {hideMoney
            ? 'Entry form changes by category type. Click Done when the day\'s record is complete.'
            : 'Quantity, selection, or automatic billing depending on category.'}
          {editingRecordId && mode === 'services' && (
            <span className="mt-1 block text-warning">Editing pending record — reception has not approved yet</span>
          )}
          {editingReturnId && mode === 'returns' && (
            <span className="mt-1 block text-warning">Editing pending return — reception has not approved yet</span>
          )}
        </CardDescription>
      </CardHeader>
      <CardContent>
        {maternity && (
          <div className="mb-5 rounded-lg border p-4">
            <p className="mb-2 text-sm font-semibold">Record subject</p>
            <div className="flex flex-wrap gap-4 text-sm">
              <label className="flex items-center gap-2">
                <input
                  type="radio"
                  name={`subject-${patientId}`}
                  checked={subjectType === 'mother'}
                  onChange={() => resetSubjectDraft('mother')}
                />
                Mother
              </label>
              <label className="flex items-center gap-2">
                <input
                  type="radio"
                  name={`subject-${patientId}`}
                  checked={subjectType === 'baby'}
                  onChange={() => resetSubjectDraft('baby')}
                  disabled={!patient?.baby}
                />
                Baby
              </label>
            </div>
            {!patient?.baby && (
              <p className="text-xs text-muted-foreground mt-2">
                Register the newborn on this maternity admission before adding baby records.
              </p>
            )}
          </div>
        )}
        <Tabs value={mode} onValueChange={setMode} className="mb-4">
          <TabsList>
            <TabsTrigger value="services">Services</TabsTrigger>
            <TabsTrigger value="returns">
              <RotateCcw className="h-4 w-4 mr-1" /> Pharmacy Returns
            </TabsTrigger>
          </TabsList>
        </Tabs>

        {mode === 'services' ? (
          <>
            <p className="mb-2 text-[11px] font-medium uppercase tracking-wider text-muted-foreground">Service category</p>
            <Tabs value={activeCategory} onValueChange={setActiveCategory}>
              <TabsList className="mb-4 flex h-auto flex-wrap gap-1 bg-muted/50 p-1">
                {categories.map((cat) => (
                  <TabsTrigger key={cat.id} value={cat.name} className="text-xs">
                    {cat.name}
                  </TabsTrigger>
                ))}
              </TabsList>
              {categories.map((cat) => (
                <TabsContent key={cat.id} value={cat.name}>
                  {activeCategory === cat.name && renderCategoryPanel()}
                </TabsContent>
              ))}
            </Tabs>

            <AnimatePresence initial={false}>
            {cart.length > 0 && (
              <motion.div
                key="service-cart"
                className="mt-6 overflow-hidden rounded-lg border"
                initial={reducedMotion ? false : fadeUp.initial}
                animate={fadeUp.animate}
                exit={fadeUp.exit}
                transition={revealTransition(reducedMotion)}
              >
                <div className="border-b bg-muted/50 px-4 py-2 text-sm font-semibold">Current record ({cart.length} items)</div>
                <div className="overflow-x-auto">
                <table className="w-full min-w-[36rem] text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Category</th>
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Service</th>
                      <th className="w-24 px-4 py-2 text-left font-medium text-muted-foreground">Qty</th>
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Notes</th>
                      {!hideMoney && <th className="px-4 py-2 text-right font-medium text-muted-foreground">Total</th>}
                      <th className="px-4 py-2"><span className="sr-only">Remove</span></th>
                    </tr>
                  </thead>
                  <tbody>
                    {cart.map((item, idx) => (
                      <tr key={item.id} className="border-b last:border-0 transition-colors duration-140 ease-out-soft hover:bg-muted/40">
                        <td className="px-4 py-2 text-muted-foreground">{item.category}</td>
                        <td className="px-4 py-2 font-medium">{item.serviceName}</td>
                        <td className="px-4 py-2">
                          <Input
                            type="number"
                            min="1"
                            className="h-8 w-20 tabular-nums"
                            value={item.quantity}
                            disabled={submitting}
                            onChange={(e) => updateCartLine(idx, { quantity: e.target.value })}
                            aria-label={`${item.serviceName} quantity`}
                          />
                        </td>
                        <td className="px-4 py-2">
                          <Input
                            className="h-8"
                            placeholder="Optional"
                            value={item.notes || ''}
                            disabled={submitting}
                            onChange={(e) => updateCartLine(idx, { notes: e.target.value })}
                            aria-label={`${item.serviceName} notes`}
                          />
                        </td>
                        {!hideMoney && <td className="px-4 py-2 text-right tabular-nums">{formatCurrency(item.total)}</td>}
                        <td className="px-4 py-2">
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                disabled={submitting}
                                onClick={() => setCart((p) => p.filter((_, i) => i !== idx))}
                                aria-label={`Remove ${item.serviceName}`}
                              >
                                <Trash2 className="h-4 w-4 text-destructive" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Remove from record</TooltipContent>
                          </Tooltip>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                </div>
              </motion.div>
            )}
            </AnimatePresence>

            {activeCat?.billingType !== BILLING_TYPES.AUTOMATIC_DAILY && (
              <div className="mt-6 flex flex-wrap items-end gap-2">
                <FormField label="Paper Slip # (optional)" className="min-w-[180px] flex-1">
                  <Input
                    placeholder="e.g. 12345"
                    value={paperSlipRef}
                    onChange={(e) => setPaperSlipRef(e.target.value)}
                    disabled={submitting}
                  />
                </FormField>
                {pendingDaily && !editingRecordId && (
                  <Button variant="outline" onClick={startEditingPendingDaily} disabled={submitting}>
                    Edit Pending Record
                  </Button>
                )}
                <Button className="flex-1 sm:flex-none" size="lg" onClick={handleDoneServices} disabled={submitting || cart.length === 0}>
                  <CheckCircle2 className="h-4 w-4 mr-2" /> {submitting ? 'Saving...' : 'Done — Save Record'}
                </Button>
              </div>
            )}
          </>
        ) : (
          <>
            <p className="mb-4 text-sm text-muted-foreground">
              Record medicines returned to pharmacy. Reception will cross-check before removing from the patient record.
            </p>
            <div className="mb-4 grid items-end gap-3 sm:grid-cols-2 lg:grid-cols-4">
              <FormField label="Medicine" className="lg:col-span-2">
                <NativeSelect
                  value={returnForm.serviceName}
                  onChange={(e) => setReturnForm((p) => ({ ...p, serviceName: e.target.value }))}
                >
                  <option value="">Select medicine...</option>
                  {pharmacyCategory?.services.map((s) => (
                    <option key={s.name} value={s.name}>{s.name}</option>
                  ))}
                </NativeSelect>
              </FormField>
              <FormField label="Quantity Returned">
                <Input
                  type="number"
                  min="1"
                  className="tabular-nums"
                  value={returnForm.quantity}
                  onChange={(e) => setReturnForm((p) => ({ ...p, quantity: e.target.value }))}
                />
              </FormField>
              <Button type="button" onClick={addToReturnCart} className="w-full">
                <Plus className="h-4 w-4 mr-1" /> Add
              </Button>
            </div>
            <FormField label="Return Reason" className="mb-4">
              <Input
                placeholder="Unused, expired, wrong order..."
                value={returnForm.reason}
                onChange={(e) => setReturnForm((p) => ({ ...p, reason: e.target.value }))}
              />
            </FormField>
            <AnimatePresence initial={false}>
            {returnCart.length > 0 && (
              <motion.div
                key="return-cart"
                className="mb-4 overflow-hidden rounded-lg border border-warning/30"
                initial={reducedMotion ? false : fadeUp.initial}
                animate={fadeUp.animate}
                exit={fadeUp.exit}
                transition={revealTransition(reducedMotion)}
              >
                <div className="border-b border-warning/30 bg-warning/10 px-4 py-2 text-sm font-semibold text-warning">
                  Return items ({returnCart.length})
                </div>
                <div className="overflow-x-auto">
                <table className="w-full min-w-[32rem] text-sm">
                  <thead>
                    <tr className="border-b">
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Medicine</th>
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Qty</th>
                      <th className="px-4 py-2 text-left font-medium text-muted-foreground">Reason</th>
                      {!hideMoney && <th className="px-4 py-2 text-right font-medium text-muted-foreground">Credit</th>}
                      <th><span className="sr-only">Remove</span></th>
                    </tr>
                  </thead>
                  <tbody>
                    {returnCart.map((item, idx) => (
                      <tr key={item.id} className="border-b last:border-0 transition-colors duration-140 ease-out-soft hover:bg-muted/40">
                        <td className="px-4 py-2 font-medium">{item.serviceName}</td>
                        <td className="px-4 py-2">
                          <Input
                            type="number"
                            min="1"
                            className="h-8 w-20 tabular-nums"
                            value={item.quantity}
                            disabled={submitting}
                            onChange={(e) => updateReturnLine(idx, { quantity: e.target.value })}
                            aria-label={`${item.serviceName} return quantity`}
                          />
                        </td>
                        <td className="px-4 py-2">
                          <Input
                            className="h-8"
                            placeholder="Reason"
                            value={item.reason || ''}
                            disabled={submitting}
                            onChange={(e) => updateReturnLine(idx, { reason: e.target.value })}
                            aria-label={`${item.serviceName} return reason`}
                          />
                        </td>
                        {!hideMoney && (
                          <td className="px-4 py-2 text-right tabular-nums text-success">-{formatCurrency(item.total)}</td>
                        )}
                        <td className="px-4 py-2">
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                disabled={submitting}
                                onClick={() => setReturnCart((p) => p.filter((_, i) => i !== idx))}
                                aria-label={`Remove ${item.serviceName}`}
                              >
                                <Trash2 className="h-4 w-4 text-destructive" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>Remove from return</TooltipContent>
                          </Tooltip>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                </div>
              </motion.div>
            )}
            </AnimatePresence>
            <div className="flex flex-wrap items-center gap-2">
              <Button size="lg" variant="destructive" onClick={handleDoneReturn} disabled={submitting || returnCart.length === 0}>
                <CheckCircle2 className="h-4 w-4 mr-2" /> {submitting ? 'Submitting...' : 'Done — Submit Return'}
              </Button>
              {pendingReturn && !editingReturnId && (
                <Button variant="outline" onClick={startEditingPendingReturn} disabled={submitting}>
                  Edit Pending Return
                </Button>
              )}
            </div>
          </>
        )}
      </CardContent>
    </Card>
    </TooltipProvider>
  )
}
