import * as React from 'react'
import { initialDailyRecords, hospitalSettings, getBedChargeForRoom } from '@/data/mockData'
import { usePatients } from '@/context/PatientsContext'
import { useBillingConfig } from '@/context/BillingConfigContext'
import { api, USE_API } from '@/api/client'
import { useAuth } from '@/context/AuthContext'

const ServiceEntriesContext = React.createContext(null)

const CURRENT_NURSE = 'Nurse Almaz Tsegaye'
const CURRENT_RECEPTIONIST = 'Sara Bekele'

function createAuditEntry(action, by, note = '') {
  return { action, by, at: new Date().toISOString(), note }
}

function todayStr() {
  return new Date().toISOString().split('T')[0]
}

function findRoomChargeIndex(records, patientId, date) {
  return records.findIndex(
    (r) =>
      r.patientId === patientId &&
      r.recordDate === date &&
      r.status !== 'rejected' &&
      r.type === 'daily_services' &&
      (r.autoType === 'room' ||
        r.services?.some((s) => s.category === 'Room Services'))
  )
}

function eachDateInclusive(start, end) {
  const dates = []
  const cur = new Date(start + 'T00:00:00')
  const last = new Date(end + 'T00:00:00')
  while (cur <= last) {
    dates.push(cur.toISOString().split('T')[0])
    cur.setDate(cur.getDate() + 1)
  }
  return dates
}

export function computeRecordTotal(record) {
  if (record.type === 'pharmacy_return') {
    return -(record.returnItems || []).reduce((s, i) => s + i.total, 0)
  }
  return (record.services || []).reduce((s, i) => s + i.total, 0)
}

function buildServiceLine({ category, serviceName, quantity, unitPrice, notes = '' }) {
  const qty = Number(quantity)
  const price = Number(unitPrice)
  return {
    id: `svc-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    category,
    serviceName,
    quantity: qty,
    unitPrice: price,
    total: qty * price,
    notes,
  }
}

function buildReturnLine({ serviceName, quantity, unitPrice, reason = '' }) {
  const qty = Number(quantity)
  const price = Number(unitPrice)
  return {
    id: `ret-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
    serviceName,
    quantity: qty,
    unitPrice: price,
    total: qty * price,
    reason,
  }
}

export function ServiceEntriesProvider({ children }) {
  const { isAuthenticated, authReady } = useAuth()
  const { getPatient, getRoomForDate } = usePatients()
  const { settings } = useBillingConfig()
  const [records, setRecords] = React.useState(() => (USE_API ? [] : initialDailyRecords))
  const [notifications, setNotifications] = React.useState(() =>
    USE_API
      ? []
      : initialDailyRecords
          .filter((r) => r.status === 'pending')
          .map((r) => ({
            id: `notif-${r.id}`,
            read: false,
            createdAt: r.recordedAt,
            type: r.type === 'pharmacy_return' ? 'pharmacy_return' : 'pending_record',
            title: r.type === 'pharmacy_return' ? 'Pharmacy Return' : 'New Daily Record',
            message: `${r.recordedBy} submitted record for ${r.recordName}`,
            patientId: r.patientId,
            recordId: r.id,
            targetRole: 'reception',
          }))
  )

  const addNotification = React.useCallback((n) => {
    setNotifications((prev) => [
      { id: Date.now(), read: false, createdAt: new Date().toISOString(), ...n },
      ...prev,
    ])
  }, [])

  const markNotificationsRead = React.useCallback(() => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })))
  }, [])

  const syncNotifications = React.useCallback((list) => {
    setNotifications(
      list
        .filter((r) => r.status === 'pending')
        .map((r) => ({
          id: `notif-${r.id}`,
          read: false,
          createdAt: r.recordedAt,
          type: r.type === 'pharmacy_return' ? 'pharmacy_return' : 'pending_record',
          title: r.type === 'pharmacy_return' ? 'Pharmacy Return' : 'New Daily Record',
          message: `${r.recordedBy} submitted record for ${r.recordName}`,
          patientId: r.patientId,
          recordId: r.id,
          targetRole: 'reception',
        }))
    )
  }, [])

  const refreshRecords = React.useCallback(async () => {
    const list = await api.getRecords()
    setRecords(list)
    syncNotifications(list)
    return list
  }, [syncNotifications])

  React.useEffect(() => {
    if (!USE_API || !authReady) return undefined
    if (!isAuthenticated) {
      setRecords([])
      setNotifications([])
      return undefined
    }
    refreshRecords().catch(console.error)
    return undefined
  }, [refreshRecords, isAuthenticated, authReady])

  const submitDailyRecord = React.useCallback(
    async ({ patientId, services, source, recordedBy, recordDate = todayStr(), existingRecordId = null, patientName = null, autoGenerated = false, autoType = null }) => {
      const patient = getPatient(patientId)
      const recordName = patientName || patient?.name
      if (!recordName || !services?.length) return null
      if (patient?.status === 'discharged' && !autoGenerated) {
        throw new Error('Cannot add inpatient services for a discharged patient.')
      }

      if (USE_API && !autoGenerated) {
        const record = await api.submitRecord(patientId, {
          services,
          source,
          recordDate,
          recordName,
        })
        setRecords((prev) => [record, ...prev.filter((r) => r.id !== record.id)])
        if (record.status === 'pending') {
          addNotification({
            type: 'pending_record',
            title: 'New Daily Record',
            message: `${recordedBy} submitted daily record for ${recordName}`,
            patientId,
            recordId: record.id,
            targetRole: 'reception',
          })
        }
        return record.id
      }

      if (USE_API && autoGenerated) return null

      const now = new Date().toISOString()
      const isReception = source === 'reception'

      const pendingExisting =
        existingRecordId ||
        (!autoGenerated &&
          records.find(
            (r) =>
              r.patientId === patientId &&
              r.recordDate === recordDate &&
              r.type === 'daily_services' &&
              r.status === 'pending' &&
              r.source === source &&
              !r.autoGenerated
          )?.id)

      if (pendingExisting) {
        setRecords((prev) =>
          prev.map((r) =>
            r.id === pendingExisting && r.status === 'pending'
              ? {
                  ...r,
                  recordName,
                  services,
                  recordedAt: now,
                  auditTrail: [
                    ...r.auditTrail,
                    createAuditEntry('edited', recordedBy, `Record updated — ${services.length} service(s)`),
                  ],
                }
              : r
          )
        )
        return pendingExisting
      }

      const record = {
        id: `REC-${Date.now()}-${Math.random().toString(36).slice(2, 5)}`,
        recordName,
        patientId,
        recordDate,
        type: 'daily_services',
        status: isReception || autoGenerated ? 'approved' : 'pending',
        source: autoGenerated ? 'system' : source,
        services,
        returnItems: [],
        autoGenerated,
        autoType,
        recordedAt: now,
        recordedBy: autoGenerated ? 'System' : recordedBy,
        reviewedAt: isReception || autoGenerated ? now : null,
        reviewedBy: isReception || autoGenerated ? (autoGenerated ? 'System' : CURRENT_RECEPTIONIST) : null,
        rejectionReason: null,
        auditTrail: [
          createAuditEntry(
            'recorded',
            autoGenerated ? 'System' : recordedBy,
            autoGenerated
              ? `Automatic ${autoType} charge for ${recordDate}`
              : `Daily record submitted — ${services.length} service(s)`
          ),
          ...((isReception || autoGenerated)
            ? [createAuditEntry('approved', autoGenerated ? 'System' : CURRENT_RECEPTIONIST, autoGenerated ? 'Auto-approved daily charge' : 'Auto-approved reception entry')]
            : []),
        ],
      }

      setRecords((prev) => [record, ...prev])

      if (!isReception && !autoGenerated) {
        addNotification({
          type: 'pending_record',
          title: 'New Daily Record',
          message: `${recordedBy} submitted daily record for ${recordName}`,
          patientId,
          recordId: record.id,
          targetRole: 'reception',
        })
      }

      return record
    },
    [getPatient, addNotification, records]
  )

  const ensureAutomaticDailyCharges = React.useCallback(
    async (patientId, throughDate = todayStr(), patientOverride = null) => {
      if (USE_API) {
        if (!isAuthenticated) return
        await refreshRecords()
        return
      }

      const patient = patientOverride ?? getPatient(patientId)
      if (!patient || patient.status === 'discharged') return

      const dates = eachDateInclusive(patient.admissionDate, throughDate)
      const doctorFee = settings.dailyDoctorVisitFee ?? hospitalSettings.dailyDoctorVisitFee
      const doctorName = settings.dailyDoctorVisitName ?? hospitalSettings.dailyDoctorVisitName

      setRecords((prev) => {
        let next = [...prev]
        let changed = false

        dates.forEach((date) => {
          const roomInfo = getRoomForDate(patient, date)
          const dailyRate = roomInfo.dailyRate ?? getBedChargeForRoom(roomInfo.room).dailyRate
          const serviceName = roomInfo.serviceName ?? getBedChargeForRoom(roomInfo.room).serviceName

          const existingRoomIdx = findRoomChargeIndex(next, patientId, date)

          const roomServiceLine = buildServiceLine({
            category: 'Room Services',
            serviceName,
            quantity: 1,
            unitPrice: dailyRate,
            notes: `Automatic room charge — ${roomInfo.room} / ${roomInfo.bed}`,
          })

          if (existingRoomIdx >= 0) {
            const existing = next[existingRoomIdx]
            const svc = existing.services?.[0]
            if (
              svc &&
              (svc.unitPrice !== dailyRate ||
                svc.serviceName !== serviceName ||
                svc.notes !== roomServiceLine.notes)
            ) {
              next[existingRoomIdx] = {
                ...existing,
                services: [roomServiceLine],
              }
              changed = true
            }
          } else {
            const now = new Date().toISOString()
            next.unshift({
              id: `REC-AUTO-ROOM-${patientId}-${date}`,
              recordName: patient.name,
              patientId,
              recordDate: date,
              type: 'daily_services',
              status: 'approved',
              source: 'system',
              autoGenerated: true,
              autoType: 'room',
              services: [roomServiceLine],
              returnItems: [],
              recordedAt: now,
              recordedBy: 'System',
              reviewedAt: now,
              reviewedBy: 'System',
              rejectionReason: null,
              auditTrail: [
                createAuditEntry('recorded', 'System', `Automatic room charge for ${date}`),
                createAuditEntry('approved', 'System', 'Auto-approved daily room charge'),
              ],
            })
            changed = true
          }

          const doctorDisabled = patient.disabledDoctorVisits?.[date]
          const hasDoctor = next.some(
            (r) =>
              r.patientId === patientId &&
              r.recordDate === date &&
              r.autoType === 'doctor' &&
              r.status !== 'rejected'
          )

          if (!doctorDisabled && !hasDoctor) {
            const now = new Date().toISOString()
            next.unshift({
              id: `REC-AUTO-DOC-${patientId}-${date}`,
              recordName: patient.name,
              patientId,
              recordDate: date,
              type: 'daily_services',
              status: 'approved',
              source: 'system',
              autoGenerated: true,
              autoType: 'doctor',
              services: [
                buildServiceLine({
                  category: 'Doctor Visits',
                  serviceName: doctorName,
                  quantity: 1,
                  unitPrice: doctorFee,
                  notes: 'Automatic daily doctor visit',
                }),
              ],
              returnItems: [],
              recordedAt: now,
              recordedBy: 'System',
              reviewedAt: now,
              reviewedBy: 'System',
              rejectionReason: null,
              auditTrail: [
                createAuditEntry('recorded', 'System', `Automatic doctor visit for ${date}`),
                createAuditEntry('approved', 'System', 'Auto-approved daily doctor visit'),
              ],
            })
            changed = true
          }

          if (doctorDisabled && hasDoctor) {
            next = next.filter(
              (r) =>
                !(
                  r.patientId === patientId &&
                  r.recordDate === date &&
                  r.autoType === 'doctor' &&
                  r.status === 'approved'
                )
            )
            changed = true
          }
        })

        return changed ? next : prev
      })
    },
    [getPatient, getRoomForDate, settings, refreshRecords, isAuthenticated]
  )

  const submitPharmacyReturn = React.useCallback(
    async ({ patientId, returnItems, source, recordedBy, recordDate = todayStr(), existingRecordId = null }) => {
      const patient = getPatient(patientId)
      if (!patient || !returnItems?.length) return null
      if (patient.status === 'discharged') {
        throw new Error('Cannot add a pharmacy return for a discharged patient.')
      }

      if (USE_API) {
        const record = await api.submitReturn(patientId, {
          returnItems,
          source,
          recordDate,
        })
        setRecords((prev) => [record, ...prev.filter((r) => r.id !== record.id)])
        if (record.status === 'pending') {
          addNotification({
            type: 'pharmacy_return',
            title: 'Pharmacy Return',
            message: `${recordedBy} submitted pharmacy return for ${patient.name}`,
            patientId,
            recordId: record.id,
            targetRole: 'reception',
          })
        }
        return record.id
      }

      const now = new Date().toISOString()
      const isReception = source === 'reception'

      if (existingRecordId) {
        setRecords((prev) =>
          prev.map((r) =>
            r.id === existingRecordId && r.status === 'pending' && r.type === 'pharmacy_return'
              ? {
                  ...r,
                  returnItems,
                  recordedAt: now,
                  auditTrail: [
                    ...r.auditTrail,
                    createAuditEntry('edited', recordedBy, `Return record updated — ${returnItems.length} item(s)`),
                  ],
                }
              : r
          )
        )
        return existingRecordId
      }

      const record = {
        id: `REC-${Date.now()}`,
        recordName: patient.name,
        patientId,
        recordDate,
        type: 'pharmacy_return',
        status: isReception ? 'approved' : 'pending',
        source,
        services: [],
        returnItems,
        recordedAt: now,
        recordedBy,
        reviewedAt: isReception ? now : null,
        reviewedBy: isReception ? CURRENT_RECEPTIONIST : null,
        rejectionReason: null,
        auditTrail: [
          createAuditEntry('recorded', recordedBy, `Pharmacy return submitted — ${returnItems.length} item(s)`),
          ...(isReception ? [createAuditEntry('approved', CURRENT_RECEPTIONIST, 'Auto-approved return')] : []),
        ],
      }

      setRecords((prev) => [record, ...prev])

      if (!isReception) {
        addNotification({
          type: 'pharmacy_return',
          title: 'Pharmacy Return',
          message: `${recordedBy} submitted pharmacy return for ${patient.name}`,
          patientId,
          recordId: record.id,
          targetRole: 'reception',
        })
      }

      return record
    },
    [getPatient, addNotification]
  )

  const getPendingEditableRecord = React.useCallback(
    (patientId, type = 'daily_services', recordDate = todayStr()) =>
      records.find(
        (r) =>
          r.patientId === patientId &&
          r.recordDate === recordDate &&
          r.type === type &&
          r.status === 'pending' &&
          r.source === 'nurse' &&
          !r.autoGenerated
      ),
    [records]
  )

  const approveRecord = React.useCallback(async (recordId, note = 'Approved by reception') => {
    if (USE_API) {
      const record = await api.approveRecord(recordId, note)
      setRecords((prev) => prev.map((r) => (r.id === recordId ? record : r)))
      return
    }

    const now = new Date().toISOString()
    setRecords((prev) =>
      prev.map((r) =>
        r.id === recordId && r.status === 'pending'
          ? {
              ...r,
              status: 'approved',
              reviewedAt: now,
              reviewedBy: CURRENT_RECEPTIONIST,
              auditTrail: [...r.auditTrail, createAuditEntry('approved', CURRENT_RECEPTIONIST, note)],
            }
          : r
      )
    )
  }, [])

  const rejectRecord = React.useCallback(async (recordId, reason = 'Rejected by reception') => {
    if (USE_API) {
      const record = await api.rejectRecord(recordId, reason)
      setRecords((prev) => prev.map((r) => (r.id === recordId ? record : r)))
      return
    }

    const now = new Date().toISOString()
    setRecords((prev) =>
      prev.map((r) =>
        r.id === recordId && r.status === 'pending'
          ? {
              ...r,
              status: 'rejected',
              reviewedAt: now,
              reviewedBy: CURRENT_RECEPTIONIST,
              rejectionReason: reason,
              auditTrail: [...r.auditTrail, createAuditEntry('rejected', CURRENT_RECEPTIONIST, reason)],
            }
          : r
      )
    )
  }, [])

  const getPatientRecords = React.useCallback(
    (patientId) =>
      records
        .filter((r) => r.patientId === patientId)
        .sort((a, b) => new Date(b.recordedAt) - new Date(a.recordedAt)),
    [records]
  )

  const getApprovedCharges = React.useCallback(
    (patientId) =>
      records
        .filter((r) => r.patientId === patientId && r.status === 'approved')
        .reduce((sum, r) => sum + computeRecordTotal(r), 0),
    [records]
  )

  const getPendingRecords = React.useCallback(
    () => records.filter((r) => r.status === 'pending').sort((a, b) => new Date(b.recordedAt) - new Date(a.recordedAt)),
    [records]
  )

  const getPendingCount = React.useCallback(() => records.filter((r) => r.status === 'pending').length, [records])

  const getUnreadNotificationCount = React.useCallback(
    () => notifications.filter((n) => !n.read && n.targetRole === 'reception').length,
    [notifications]
  )

  const getRecentRecords = React.useCallback(
    (limit = 10) => [...records].sort((a, b) => new Date(b.recordedAt) - new Date(a.recordedAt)).slice(0, limit),
    [records]
  )

  const getPatientBalance = React.useCallback(
    (patient) => {
      const approved = getApprovedCharges(patient.id)
      const pending = records
        .filter((r) => r.patientId === patient.id && r.status === 'pending' && r.type === 'daily_services')
        .reduce((s, r) => s + computeRecordTotal(r), 0)
      return {
        totalCharges: approved,
        remainingBalance: patient.deposit - approved,
        pendingCharges: pending,
      }
    },
    [records, getApprovedCharges]
  )

  const getBalanceStatus = React.useCallback(
    (patient) => {
      const { remainingBalance } = getPatientBalance(patient)
      const threshold = settings.lowBalanceThreshold ?? hospitalSettings.lowBalanceThreshold
      if (remainingBalance >= threshold * 2) return 'sufficient'
      if (remainingBalance >= threshold) return 'low'
      return 'critical'
    },
    [getPatientBalance, settings]
  )

  const getApprovedLineItems = React.useCallback(
    (patientId) => {
      const items = []
      records
        .filter((r) => r.patientId === patientId && r.status === 'approved')
        .sort((a, b) => new Date(a.recordedAt) - new Date(b.recordedAt))
        .forEach((r) => {
          if (r.type === 'pharmacy_return') {
            r.returnItems.forEach((item) => {
              items.push({
                id: item.id,
                date: r.recordDate,
                department: 'Pharmacy Return',
                item: item.serviceName,
                quantity: item.quantity,
                price: item.unitPrice,
                total: -item.total,
                source: r.source,
                recordName: r.recordName,
              })
            })
          } else {
            r.services.forEach((s) => {
              items.push({
                id: s.id,
                date: r.recordDate,
                department: s.category,
                item: s.serviceName,
                quantity: s.quantity,
                price: s.unitPrice,
                total: s.total,
                source: r.source,
                recordName: r.recordName,
              })
            })
          }
        })
      return items
    },
    [records]
  )

  const value = {
    records,
    notifications,
    submitDailyRecord,
    submitPharmacyReturn,
    getPendingEditableRecord,
    approveRecord,
    rejectRecord,
    getPatientRecords,
    getApprovedCharges,
    getPendingRecords,
    getPendingCount,
    getUnreadNotificationCount,
    getRecentRecords,
    getPatientBalance,
    getBalanceStatus,
    getApprovedLineItems,
    markNotificationsRead,
    refreshRecords,
    buildServiceLine,
    buildReturnLine,
    ensureAutomaticDailyCharges,
    CURRENT_NURSE,
    CURRENT_RECEPTIONIST,
    entries: records,
    approveEntry: approveRecord,
    rejectEntry: rejectRecord,
    getPendingEntries: getPendingRecords,
    getPatientEntries: getPatientRecords,
    getRecentActivities: getRecentRecords,
  }

  return <ServiceEntriesContext.Provider value={value}>{children}</ServiceEntriesContext.Provider>
}

export function useServiceEntries() {
  const ctx = React.useContext(ServiceEntriesContext)
  if (!ctx) throw new Error('useServiceEntries must be used within ServiceEntriesProvider')
  return ctx
}
