import mongoose from 'mongoose'

const serviceLineSchema = new mongoose.Schema(
  {
    id: String,
    category: String,
    serviceName: String,
    quantity: { type: Number, default: 1 },
    unitPrice: Number,
    total: Number,
    notes: String,
  },
  { _id: false }
)

const returnLineSchema = new mongoose.Schema(
  {
    id: String,
    serviceName: String,
    quantity: Number,
    unitPrice: Number,
    total: Number,
    reason: String,
  },
  { _id: false }
)

const auditEntrySchema = new mongoose.Schema(
  { action: String, by: String, at: String, note: String },
  { _id: false }
)

const serviceRecordSchema = new mongoose.Schema(
  {
    patientId: { type: String, required: true, index: true },
    recordName: String,
    date: { type: String, required: true },
    status: { type: String, enum: ['pending', 'approved', 'rejected'], default: 'pending' },
    recordType: { type: String, enum: ['daily', 'return', 'manual'], default: 'daily' },
    source: { type: String, enum: ['nurse', 'reception', 'system'], default: 'nurse' },
    autoType: { type: String, enum: ['room', 'doctor'], default: null },
    autoGenerated: { type: Boolean, default: false },
    services: [serviceLineSchema],
    returnItems: [returnLineSchema],
    submittedBy: String,
    approvedBy: String,
    rejectionReason: String,
    recordedAt: Date,
    reviewedAt: Date,
    auditTrail: [auditEntrySchema],
  },
  { timestamps: true }
)

serviceRecordSchema.index({ patientId: 1, date: 1, autoType: 1 })

export const ServiceRecord = mongoose.model('ServiceRecord', serviceRecordSchema)
