import { ServiceRecord } from '../models/ServiceRecord.js'
import { RoomAssignment } from '../models/RoomAssignment.js'
import { HospitalSettings } from '../models/HospitalSettings.js'
import { Patient } from '../models/Patient.js'

const BED_TYPES = {
  'General Ward': { serviceName: 'General Ward - Daily Rate', dailyRate: 1500 },
  'Private Room': { serviceName: 'Private Room - Daily Rate', dailyRate: 5000 },
  ICU: { serviceName: 'ICU - Daily Rate', dailyRate: 8000 },
  Operation: { serviceName: 'Operation Room - Daily Rate', dailyRate: 10000 },
}

function eachDateInclusive(start, end) {
  const dates = []
  const d = new Date(start + 'T12:00:00')
  const last = new Date(end + 'T12:00:00')
  while (d <= last) {
    dates.push(d.toISOString().slice(0, 10))
    d.setDate(d.getDate() + 1)
  }
  return dates
}

async function getRoomForDate(patientId, date) {
  const assignment = await RoomAssignment.findOne({
    patientId,
    startDate: { $lte: date },
    $or: [{ endDate: null }, { endDate: { $gt: date } }],
  }).sort({ startDate: -1 })

  if (assignment) {
    return {
      room: assignment.roomType,
      bed: assignment.bedLabel,
      dailyRate: assignment.dailyRate,
      serviceName: BED_TYPES[assignment.roomType]?.serviceName || `${assignment.roomType} - Daily Rate`,
    }
  }
  return null
}

function computeRecordTotal(r) {
  if (r.recordType === 'return') {
    return -(r.returnItems?.reduce((s, i) => s + (i.total || 0), 0) || 0)
  }
  return r.services?.reduce((s, line) => s + (line.total || 0), 0) || 0
}

async function upsertAutoRecord(patient, date, autoType, line) {
  const existing = await ServiceRecord.findOne({ patientId: patient.patientId, date, autoType })
  const now = new Date()
  if (existing) {
    existing.services = [line]
    existing.status = 'approved'
    existing.recordName = patient.name
    existing.autoGenerated = true
    existing.source = 'system'
    existing.submittedBy = 'System'
    existing.approvedBy = 'System'
    existing.reviewedAt = now
    await existing.save()
    return existing
  }
  return ServiceRecord.create({
    patientId: patient.patientId,
    recordName: patient.name,
    date,
    status: 'approved',
    recordType: 'daily',
    autoType,
    autoGenerated: true,
    source: 'system',
    services: [line],
    submittedBy: 'System',
    approvedBy: 'System',
    recordedAt: now,
    reviewedAt: now,
    auditTrail: [
      { action: 'recorded', by: 'System', at: now.toISOString(), note: `Automatic ${autoType} charge for ${date}` },
      { action: 'approved', by: 'System', at: now.toISOString(), note: 'Auto-approved daily charge' },
    ],
  })
}

export async function ensureAutomaticDailyCharges(patient, throughDate) {
  if (!patient || patient.status === 'discharged') return []

  const settings = (await HospitalSettings.findOne({ key: 'default' })) || {}
  const doctorFee = settings.dailyDoctorVisitFee ?? 2000
  const doctorName = settings.dailyDoctorVisitName ?? 'Daily Doctor Visit'
  const end = throughDate || new Date().toISOString().slice(0, 10)
  const dates = eachDateInclusive(patient.admissionDate, end)
  const created = []

  for (const date of dates) {
    const roomInfo = await getRoomForDate(patient.patientId, date)
    if (roomInfo) {
      const roomLine = {
        category: 'Room Services',
        serviceName: roomInfo.serviceName,
        quantity: 1,
        unitPrice: roomInfo.dailyRate,
        total: roomInfo.dailyRate,
        notes: `Automatic room charge — ${roomInfo.room} / ${roomInfo.bed}`,
      }
      created.push(await upsertAutoRecord(patient, date, 'room', roomLine))
    }

    const doctorDisabled = patient.disabledDoctorVisitDates?.includes(date)
    if (doctorDisabled) {
      await ServiceRecord.deleteOne({ patientId: patient.patientId, date, autoType: 'doctor' })
    } else {
      const doctorLine = {
        category: 'Doctor Visits',
        serviceName: doctorName,
        quantity: 1,
        unitPrice: doctorFee,
        total: doctorFee,
        notes: 'Automatic daily doctor visit',
      }
      created.push(await upsertAutoRecord(patient, date, 'doctor', doctorLine))
    }
  }

  return created
}

export async function setDoctorVisitDisabled(patientId, date, disabled) {
  const patient = await Patient.findOne({ patientId })
  if (!patient) return null

  const dates = patient.disabledDoctorVisitDates || []
  if (disabled) {
    if (!dates.includes(date)) dates.push(date)
    await ServiceRecord.deleteOne({ patientId, date, autoType: 'doctor' })
  } else {
    patient.disabledDoctorVisitDates = dates.filter((d) => d !== date)
    await patient.save()
    await ensureAutomaticDailyCharges(patient, date)
    return patient
  }

  patient.disabledDoctorVisitDates = dates
  await patient.save()
  return patient
}

export async function calcPatientBalance(patientId) {
  const records = await ServiceRecord.find({ patientId, status: 'approved' })
  const totalCharges = records.reduce((sum, r) => sum + computeRecordTotal(r), 0)
  const patient = await Patient.findOne({ patientId })
  const depositTotal = patient?.depositTotal ?? 0
  return { totalCharges, depositTotal, balance: depositTotal - totalCharges }
}
