import { ServiceRecord } from '../models/ServiceRecord.js'
import { RoomAssignment } from '../models/RoomAssignment.js'
import { DoctorAssignment } from '../models/DoctorAssignment.js'
import { Patient } from '../models/Patient.js'
import { HospitalSettings } from '../models/HospitalSettings.js'
import { todayStr, eachDateInclusive, clampChargeDate } from '../utils/dates.js'
import { loadResolvedSettings } from '../utils/settings.js'

const BED_TYPES = {
  'General Ward': { serviceName: 'General Ward - Daily Rate', dailyRate: 1500 },
  'Private Room': { serviceName: 'Private Room - Daily Rate', dailyRate: 5000 },
  ICU: { serviceName: 'ICU - Daily Rate', dailyRate: 8000 },
  Operation: { serviceName: 'Operation Room - Daily Rate', dailyRate: 10000 },
  'Delivery Room': { serviceName: 'Delivery Room - Daily Rate', dailyRate: 1500 },
}

export { eachDateInclusive, todayStr } from '../utils/dates.js'

export function chargeDatesForPatient(patient, throughDate, { range = false } = {}) {
  const today = todayStr()
  const admissionDate = patient?.admissionDate
  if (!admissionDate) return []
  const requested = throughDate || today
  if (range) {
    const start = admissionDate > today ? null : admissionDate
    const end = requested > today ? today : requested
    if (!start || !end || end < start) return []
    return eachDateInclusive(start, end).filter((date) => clampChargeDate(date, admissionDate, today))
  }
  const date = clampChargeDate(requested, admissionDate, today)
  return date ? [date] : []
}

export function assignmentCoversDate(assignment, date) {
  if (!assignment?.effectiveFrom) return false
  if (assignment.effectiveFrom > date) return false
  if (assignment.effectiveTo && assignment.effectiveTo <= date) return false
  return true
}

export function doctorLineKey(line) {
  return String(line.doctorId || line.id || '')
}

export function mergeDoctorVisitLines(existingServices = [], desiredLines = []) {
  const byKey = new Map()
  for (const line of existingServices) {
    const key = doctorLineKey(line)
    if (key) byKey.set(key, line)
    else byKey.set(`legacy-${byKey.size}`, line)
  }
  for (const line of desiredLines) {
    const key = doctorLineKey(line)
    if (!key || byKey.has(key)) continue
    byKey.set(key, line)
  }
  return [...byKey.values()]
}

export function buildDoctorVisitLine(assignment, fallbackFee = 0) {
  const snapshot = Number(assignment.visitPriceSnapshot)
  const price = Number.isFinite(snapshot) && snapshot > 0 ? snapshot : Number(fallbackFee) || 0
  return {
    id: `doc-${assignment.doctorId}`,
    category: 'Doctor Visits',
    serviceName: `${assignment.doctorNameSnapshot} — Daily Visit`,
    quantity: 1,
    unitPrice: price,
    total: price,
    notes: `${assignment.specialtySnapshot} · ${snapshot > 0 ? `price snapshot ${price}` : `settings fallback ${price}`}`,
    doctorId: assignment.doctorId,
    specialty: assignment.specialtySnapshot,
  }
}

async function getRoomForDate(patientId, date) {
  const assignment = await RoomAssignment.findOne({
    patientId,
    startDate: { $lte: date },
    $or: [{ endDate: null }, { endDate: { $gt: date } }],
  }).sort({ startDate: -1 })

  if (assignment) {
    return {
      room: assignment.roomType,
      bed: assignment.bedLabel,
      dailyRate: assignment.dailyRate,
      serviceName: BED_TYPES[assignment.roomType]?.serviceName || `${assignment.roomType} - Daily Rate`,
    }
  }
  return null
}

function computeRecordTotal(r) {
  if (r.recordType === 'return') {
    return -(r.returnItems?.reduce((s, i) => s + (i.total || 0), 0) || 0)
  }
  return r.services?.reduce((s, line) => s + (line.total || 0), 0) || 0
}

function linesEqual(a = [], b = []) {
  if (a.length !== b.length) return false
  return JSON.stringify(a) === JSON.stringify(b)
}

async function upsertAutoRecord(patient, date, autoType, lines) {
  const existing = await ServiceRecord.findOne({ patientId: patient.patientId, date, autoType })
  const now = new Date()
  const serviceLines = Array.isArray(lines) ? lines : [lines]

  if (existing) {
    const nextServices = autoType === 'doctor' ? mergeDoctorVisitLines(existing.services, serviceLines) : serviceLines
    if (linesEqual(existing.services, nextServices) && existing.status === 'approved') return existing
    existing.services = nextServices
    existing.status = 'approved'
    existing.recordName = patient.name
    existing.autoGenerated = true
    existing.source = 'system'
    existing.submittedBy = 'System'
    existing.approvedBy = 'System'
    existing.reviewedAt = now
    try {
      await existing.save()
    } catch (err) {
      if (err?.code !== 11000) throw err
    }
    return existing
  }

  try {
    return await ServiceRecord.create({
      patientId: patient.patientId,
      recordName: patient.name,
      date,
      status: 'approved',
      recordType: 'daily',
      autoType,
      autoGenerated: true,
      source: 'system',
      services: serviceLines,
      submittedBy: 'System',
      approvedBy: 'System',
      recordedAt: now,
      reviewedAt: now,
      auditTrail: [
        { action: 'recorded', by: 'System', at: now.toISOString(), note: `Automatic ${autoType} charge for ${date}` },
        { action: 'approved', by: 'System', at: now.toISOString(), note: 'Auto-approved daily charge' },
      ],
    })
  } catch (err) {
    if (err?.code !== 11000) throw err
    return ServiceRecord.findOne({ patientId: patient.patientId, date, autoType })
  }
}

export async function ensureAutomaticDailyCharges(patient, throughDate, options = {}) {
  if (!patient || patient.status === 'discharged') return []

  const dates = chargeDatesForPatient(patient, throughDate, options)
  const [assignments, rules] = await Promise.all([
    DoctorAssignment.find({ patientId: patient.patientId }),
    loadResolvedSettings(HospitalSettings),
  ])
  const fallbackDoctorFee = Number(rules.dailyDoctorVisitFee) || 0
  const created = []

  for (const date of dates) {
    const roomInfo = await getRoomForDate(patient.patientId, date)
    if (roomInfo) {
      const roomLine = {
        category: 'Room Services',
        serviceName: roomInfo.serviceName,
        quantity: 1,
        unitPrice: roomInfo.dailyRate,
        total: roomInfo.dailyRate,
        notes: `Automatic room charge — ${roomInfo.room} / ${roomInfo.bed}`,
      }
      created.push(await upsertAutoRecord(patient, date, 'room', roomLine))
    }

    const doctorDisabled = patient.disabledDoctorVisitDates?.includes(date)
    if (doctorDisabled) {
      await ServiceRecord.deleteOne({ patientId: patient.patientId, date, autoType: 'doctor' })
      continue
    }

    const covering = assignments.filter((a) => assignmentCoversDate(a, date))
    if (!covering.length) continue
    const doctorLines = covering.map((assignment) => buildDoctorVisitLine(assignment, fallbackDoctorFee))
    created.push(await upsertAutoRecord(patient, date, 'doctor', doctorLines))
  }

  return created
}

export async function setDoctorVisitDisabled(patientId, date, disabled) {
  const patient = await Patient.findOne({ patientId })
  if (!patient) return null

  const dates = patient.disabledDoctorVisitDates || []
  if (disabled) {
    if (!dates.includes(date)) dates.push(date)
    await ServiceRecord.deleteOne({ patientId, date, autoType: 'doctor' })
  } else {
    patient.disabledDoctorVisitDates = dates.filter((d) => d !== date)
    await patient.save()
    await ensureAutomaticDailyCharges(patient, date)
    return patient
  }

  patient.disabledDoctorVisitDates = dates
  await patient.save()
  return patient
}

export async function calcPatientBalance(patientId) {
  const records = await ServiceRecord.find({ patientId, status: 'approved' })
  const totalCharges = records.reduce((sum, r) => sum + computeRecordTotal(r), 0)
  const patient = await Patient.findOne({ patientId })
  const depositTotal = patient?.depositTotal ?? 0
  return { totalCharges, depositTotal, balance: depositTotal - totalCharges }
}

export async function runDailyChargesForActivePatients(throughDate) {
  const patients = await Patient.find({ status: { $ne: 'discharged' } })
  const end = throughDate || todayStr()
  let processed = 0
  for (const patient of patients) {
    await ensureAutomaticDailyCharges(patient, end)
    processed += 1
  }
  return { processed, throughDate: end }
}
