import { Patient } from '../models/Patient.js'
import { ServiceRecord } from '../models/ServiceRecord.js'
import { roleHasPermission } from '../utils/permissions.js'
import { escapeRegex } from './globalSearch.js'
import { recordAmount, recordTypeForPanel } from './receptionDashboard.js'

export const RECEPTION_RECENTLY_APPROVED_PERMISSION = 'admissions.edit'
export const RECENT_APPROVED_LIMIT = 100

function defaultDeps() {
  return { Patient, ServiceRecord }
}

function forbidUnless(allowed) {
  if (allowed) return
  const error = new Error('Forbidden')
  error.status = 403
  throw error
}

function typeFilter(query) {
  const type = String(query.type || '').trim()
  if (type === 'return' || type === 'pharmacy_return') return 'return'
  if (type === 'daily' || type === 'daily_services') return 'daily'
  return null
}

function serviceSummary(doc) {
  const lines = doc.recordType === 'return' ? doc.returnItems : doc.services
  return (lines || [])
    .map((line) => line.serviceName)
    .filter(Boolean)
    .slice(0, 3)
    .join(', ')
}

async function matchingPatientIds(PatientModel, rx) {
  const found = PatientModel.find({ $or: [{ name: rx }, { patientId: rx }] }).select('patientId')
  const rows = typeof found?.lean === 'function' ? await found.lean() : await found
  return rows.map((row) => row.patientId).filter(Boolean)
}

function recordMatch(query) {
  const filter = { status: 'approved' }
  const recordType = typeFilter(query)
  if (recordType) filter.recordType = recordType

  const q = String(query.q || '').trim()
  return { filter, q }
}

export function mapRecentlyApprovedRecord(doc, patientName = '') {
  const amount = recordAmount(doc)
  const itemCount =
    doc.recordType === 'return' ? doc.returnItems?.length || 0 : doc.services?.length || 0
  return {
    id: String(doc._id),
    patientId: doc.patientId,
    patientName: patientName || '',
    recordName: doc.recordName || patientName || '',
    type: recordTypeForPanel(doc.recordType),
    serviceSummary: serviceSummary(doc),
    itemCount,
    amount,
    status: doc.status,
    recordedBy: doc.submittedBy || '',
    recordedAt: doc.recordedAt?.toISOString?.() || doc.createdAt?.toISOString?.() || null,
    approvedBy: doc.approvedBy || null,
    reviewedAt: doc.reviewedAt?.toISOString?.() || null,
    autoGenerated: Boolean(doc.autoGenerated),
  }
}

export async function buildReceptionRecentlyApproved(auth, query = {}, injected = {}) {
  forbidUnless(roleHasPermission(auth?.role, RECEPTION_RECENTLY_APPROVED_PERMISSION))
  const deps = { ...defaultDeps(), ...injected }
  const { filter, q } = recordMatch(query)

  if (q) {
    const rx = new RegExp(escapeRegex(q), 'i')
    const patientIds = await matchingPatientIds(deps.Patient, rx)
    filter.$or = [
      { patientId: { $in: patientIds } },
      { patientId: rx },
      { recordName: rx },
      { approvedBy: rx },
    ]
  }

  const found = deps.ServiceRecord.find(filter)
    .select(
      'patientId recordName recordType status services returnItems submittedBy recordedAt createdAt approvedBy reviewedAt autoGenerated'
    )
    .sort({ reviewedAt: -1, createdAt: -1 })
    .limit(RECENT_APPROVED_LIMIT)
  const docs = typeof found?.lean === 'function' ? await found.lean() : await found

  const ids = [...new Set(docs.map((doc) => doc.patientId).filter(Boolean))]
  const nameQuery = ids.length ? deps.Patient.find({ patientId: { $in: ids } }).select('patientId name') : null
  const nameDocs = nameQuery
    ? typeof nameQuery.lean === 'function'
      ? await nameQuery.lean()
      : await nameQuery
    : []
  const namesById = Object.fromEntries(nameDocs.map((doc) => [doc.patientId, doc.name]))

  const rows = docs.map((doc) => mapRecentlyApprovedRecord(doc, namesById[doc.patientId] || ''))
  const amountTotal = rows.reduce((sum, row) => sum + row.amount, 0)

  return {
    summary: {
      records: rows.length,
      amountTotal,
    },
    rows,
    generatedAt: new Date().toISOString(),
  }
}
